### ISSUE TITLE
HTTP 3GP mobile fails to load

### ISSUE THREAD

**Issue by Preloading** [ftde0/yt2009#132]
I am trying to get yt2009 web to work on my iphone 3g. It doesn't support modern codecs and file containers like mp4, so it requires 3GP. When you change the rstp flag to HTTP 3GP, the mobile video feed fails to load. (this also occurs on my PC.) It attempts to load till it times out. Nothing appeared in the output. This is normally under an apache proxy, but still occurs when connecting directly.

Here is my docker compose if it helps
```
services:
  yt2009:
    container_name: yt2009
    build: /opt/yt2009/repo/
    
    ports:
      - 3050:3050
    environment:
      - YT2009_ENV=prod
      - YT2009_IP=https://DOMAIN_HERE
      - YT2009_PORT=3050
      - YT2009_TOKENS=passphrase
      - YT2009_LOGGED_TOKENS=passphrase
      - YT2009_GDATA_AUTH=true
    volumes:
      - "/opt/yt2009/certs:/yt2009/certs"
      - "/yt2009/assets/site-assets"
      - "/opt/yt2009/assets:/yt2009/assets"
      - "/opt/yt2009/logs/access.log:/data/accessdata"
    restart: unless-stopped
```
